// Autogenerated file
import ShaderProgram from '../shaderprogram';

export default class Shader extends ShaderProgram {
  aPosition: number;
  aTexcoord: number;
  aShade: number;

  uView: WebGLUniformLocation;
  uProjection: WebGLUniformLocation;
  uFogColor: WebGLUniformLocation;
  uFogDensity: WebGLUniformLocation;
  uLights: WebGLUniformLocation;
  uWallTexture: WebGLUniformLocation;

  
  constructor(gl: WebGLRenderingContext) {
    super(gl, Shader.vsSource, Shader.fsSource);
  }
  

  static vsSource = `
attribute vec4  position;
attribute vec2  texcoord;

attribute float shade;

uniform mat4 view;
uniform mat4 projection;

varying highp float f_shade;
varying vec2        f_texcoord;
varying vec4        f_position;

void main() {
  gl_Position = projection * view * position;
  f_shade     = shade;
  f_texcoord  = texcoord;
  f_position  = position;
}

`;
  static fsSource = `
uniform highp vec4  fogColor;
uniform highp float fogDensity;

highp vec4 mix_fog(highp vec4 base_color) {
  highp float dist = gl_FragCoord.z / gl_FragCoord.w;
  highp float fog  = 1.0 / exp(dist * fogDensity);
  fog = clamp(fog, 0.0, 1.0);
  return mix(fogColor, base_color, fog);
}

uniform highp vec4 lights[16];

highp vec3 mixLight(highp vec3 fragment, highp vec3 position) {
  for (int i = 0; i < 16; ++i) {
    highp float d = distance(lights[i].xyz, position);
    highp float a = (lights[i].w - d) / (lights[i].w + 0.001);
    a = clamp(a, 0.0, 1.0);
    fragment = mix(fragment, vec3(0.85, 0.55, 0.18), a);
  }
  return fragment;
}


varying highp float f_shade;
varying highp vec2  f_texcoord;
varying highp vec4  f_position;

uniform sampler2D   wallTexture;



void main() {
  highp vec4 base_color = texture2D(wallTexture, f_texcoord);
  gl_FragColor = mix_fog(base_color);
  gl_FragColor.xyz = mixLight(gl_FragColor.xyz, f_position.xyz);
}

`;
}
