// Autogenerated file
import ShaderProgram from '../shaderprogram';

export default class Shader extends ShaderProgram {
  aPosition: number;
  aTexcoord: number;

  uProjection: WebGLUniformLocation;
  uSwingProgress: WebGLUniformLocation;
  uWeaponTexture: WebGLUniformLocation;

  
  constructor(gl: WebGLRenderingContext) {
    super(gl, Shader.vsSource, Shader.fsSource);
  }
  

  static vsSource = `
attribute vec4 position;
attribute vec2 texcoord;

uniform mat4 projection;

varying highp vec2 f_texcoord;

uniform mediump float swingProgress;

void main() {
  mediump vec4 swingPosition = position;
  swingPosition.x -= swingProgress;
  swingPosition.y -= swingProgress;

  gl_Position = projection * swingPosition;
  f_texcoord = texcoord;
}

`;
  static fsSource = `
varying highp vec2 f_texcoord;
uniform sampler2D weaponTexture;

void main() {
  gl_FragColor = texture2D(weaponTexture, f_texcoord);
}

`;
}
